### ISSUE TITLE
dcm_to_quat followed by quat_to_dcm return a different DCM

### ISSUE THREAD

**Issue by rmcaixeta** [JuliaSpace/ReferenceFrameRotations.jl#11]
Hi

First, I've been using ReferenceFrameRotations.jl for some time for 3D rotation, it's great, thanks for making it available
My issue here is with the following operation:

```julia
q = dcm_to_quat(dcm1)
dcm2 = quat_to_dcm(q)
```

In most cases, `dcm1 == dcm2`. But for some values this doesn't happen. Here one of the cases I found:

```julia
julia> dcm1 = DCM([-0.997512 0.0704939 0.0; 0.0704939 0.997512 0.0; 0.0 0.0 1.0])
3×3 StaticArrays.SArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
 -0.997512   0.0704939  0.0
  0.0704939  0.997512   0.0
  0.0        0.0        1.0

julia> q = dcm_to_quat(dcm1)
Quaternion{Float64}:
  + 0.7071067811865476 + 0.0.i + 0.0.j + 0.0.k

julia> dcm2 = quat_to_dcm(q)
3×3 StaticArrays.SArray{Tuple{3,3},Float64,2,9} with indices SOneTo(3)×SOneTo(3):
 0.5  0.0  0.0
 0.0  0.5  0.0
 0.0  0.0  0.5
``` 

Any idea of what it can be?

**Comment by ronisbr** [comment]
Hi @rmcaixeta !

> First, I've been using ReferenceFrameRotations.jl for some time for 3D rotation, it's great, thanks for making it available

Nice! I am glad it is being useful.

> Any idea of what it can be?

I do not have a computer right now to test. However, if your first matrix tries to describe a rotation about the Z axis, then the first two components in the diagonal should be equal (https://en.wikipedia.org/wiki/Rotation_matrix).

Your matrix seems to describe a transformation that is not a pure rotation. It contains a reflection of the X-axis. Hence, the algorithms does not work, leading to a invalid quaternion, and then to an invalid DCM.

**Comment by rmcaixeta** [comment]
Ahh got it. I'm building the DCM from eigenvectors (both 2D and 3D cases). Now I preprocessed the eigenvectors making some reflection to guarantee det(DCM) == 1 whenever necessary. Working perfectly, thanks!

**Comment by ronisbr** [comment]
Excellent! :)
