### ISSUE TITLE
Refactor EulerAngles and EulerAngleAxis

### ISSUE THREAD

**Issue by juliohm** [JuliaSpace/ReferenceFrameRotations.jl#20]
I think we can potentially simplify things if we refactor these two representations. Could you please clarify if one can be easily represented in terms of the other? I understand that EulerAngleAxis is a rotation around an arbitrary unitary vector whereas EulerAngles are rotations specified in terms of the canonical basis. Can the latter be written in terms of the former as a sequence of rotations with pre-defined static vectors? What is the benefit of keeping them separate as two separate structs?

After we sort out the redundancy, I think we could make things more static and turn `rot_seq` simply a utility function. We could write something like `basis(:X)` to get `(1,0,0)` an `basis(:XY)` to return a list of such basis vectors. Does that make sense?

This will help define conversion methods.

**Comment by ronisbr** [comment]
Hi @juliohm !

`EulerAngleAxis` is a geometric representation (a rotation of an angle about one axis) of how a quaternion works. The Euler Angles are a more meaningful description of rotations that is mostly used to analyze data. We can develop equations to convert from one to another but I just cannot see the point.

Those types exist to analyze rotations from different perspectives, they cannot be merged.

> After we sort out the redundancy, I think we could make things more static and turn `rot_seq` simply a utility function. We could write something like `basis(:X)` to get `(1,0,0)` an `basis(:XY)` to return a list of such basis vectors. Does that make sense?

I really did not understand, can you please clarify?

**Comment by juliohm** [comment]
Hi @ronisbr !

> Those types exist to analyze rotations from different perspectives, they cannot be merged.

You want to keep them separate so that users can choose between different ways of representing rotations, right?

> > After we sort out the redundancy, I think we could make things more static and turn `rot_seq` simply a utility function. We could write something like `basis(:X)` to get `(1,0,0)` an `basis(:XY)` to return a list of such basis vectors. Does that make sense?
> 
> I really did not understand, can you please clarify?

I thought initially from the names of the structs that `EulerAngles(theta1, theta2, theta3) = EulerAngleAxis(theta1, (1,0,0)) * EulerAngleAxis(theta2, (0,1,0)) * EulerAngleAxis(theta3, (0,0,1))` or some permutation of these factors. If that is the case, then it can make sense to merge the internal implementations. Users could still choose between the two structs, but internally they would be implemented in terms of a single function that does successive rotations around specific vectors X, Y, Z. Am I missing something?

**Comment by ronisbr** [comment]
> I thought initially from the names of the structs that `EulerAngles(theta1, theta2, theta3) = EulerAngleAxis(theta1, (1,0,0)) * EulerAngleAxis(theta2, (0,1,0)) * EulerAngleAxis(theta3, (0,0,1))` or some permutation of these factors. If that is the case, then it can make sense to merge the internal implementations. Users could still choose between the two structs, but internally they would be implemented in terms of a single function that does successive rotations around specific vectors X, Y, Z. Am I missing something?

Oh, yes, the Euler angles representation can be written as you proposed using the EulerAngleAxis. However, I really do not see the point. IIUC, this will only add computational burden of converting Euler angles to EulerAngleAxis without any gain. I really cannot see what we will simplify in the current implementation. Notice that it is very important to have a EulerAngles structure so that the users can see those angles when converting from DCM or Quaternions.

**Comment by ronisbr** [comment]
I will close this because I think it was handled using the conversion methods in `master`. With Euler angles, I created a "helper" private structure so that you can do:

```julia
julia> d = rand(DCM)
DCM{Float64}:
 -0.96356    0.183948  -0.194204
 -0.0820236  0.487857   0.869061
  0.254606   0.853322  -0.454991

julia> convert(EulerAngles(:XYX), d)
EulerAngles{Float64}:
  R(X) :  0.758285 rad  ( 43.4465°)
  R(Y) :  2.8708   rad  ( 164.485°)
  R(X) : -0.31166  rad  (-17.8568°)

julia> convert(EulerAngles(:ZYX), d)
EulerAngles{Float64}:
  R(Z) :  2.95296  rad  ( 169.192°)
  R(Y) :  0.195446 rad  ( 11.1982°)
  R(X) :  2.0531   rad  ( 117.634°)
```
