### ISSUE TITLE
Cannot update to latest version?

### ISSUE THREAD

**Issue by arbenede** [JuliaSpace/ReferenceFrameRotations.jl#24]
For some reason I cannot update `ReferenceFrameRotations` to the latest version because of a conflict with `SatelliteToolbox`, that I am also `using` by the way:

```
(@v1.8) pkg> status --outdated ReferenceFrameRotations
Status `~/.julia/environments/v1.8/Project.toml`
⌅ [74f56ac7] ReferenceFrameRotations v1.0.1 (<v3.0.0): SatelliteToolbox
```
Any ideas? Should I delete `~/.julia/registries/General.tar.gz` and recreate it?

**Comment by ronisbr** [comment]
This should be fix by now!
