### ISSUE TITLE
How to cite this package?

### ISSUE THREAD

**Issue by cdelv** [JuliaSpace/ReferenceFrameRotations.jl#26]
Hi, I've been using this package for a long time and I love it. Really good work.

I wanted to know, how do I cite it? Are there any citations to the theory used to write the package? Where can I find it?

Best regards.

**Comment by ronisbr** [comment]
Hi @cdelv !

Thanks! I am glad it is being useful.

I have not published yet any paper describing this package (it is in my TODO list). The theory can be found in books like:

https://www.amazon.com.br/Spacecraft-Attitude-Dynamics-Peter-Hughes/dp/0486439259

**Comment by cdelv** [comment]
Great, thank you very much.
