### ISSUE TITLE
dcm_to_quat may have wrong sign on the img part

### ISSUE THREAD

**Issue by gzhang8** [JuliaSpace/ReferenceFrameRotations.jl#8]
I recently find `dcm_to_quat` is not consistent with the one https://github.com/FugroRoames/Rotations.jl 

The later gives me the correct result, but I haven't closely inspected code in both. Maybe it is still useful to pass the information here.

**Comment by ronisbr** [comment]
Hi @gzhang8 

Thanks for the reporting. However, keep in mind that Rotations.jl always perform active rotations:

> This package assumes active (right handed) rotations where applicable.

This means that it rotates vectors in coordinate systems. ReferenceFrameRotations.jl, on the other hand, always perform passive rotations, i.e. it rotates the reference systems. This is way the result is inverted.

**Comment by gzhang8** [comment]
I see. Thanks for the information. New knowledge learned :+1:
